ValSubstantivo = input("Insira um substantivo:")
ValAdjetivo = input("Insira um adjetivo:")
ValVerbo = input("Insira um verbo:")
print ("A frase formada é:")
print ("O(A)",ValSubstantivo,"", ValAdjetivo ,"", ValVerbo)
